BEGIN TRANSACTION;

CREATE TABLE EXEMPLO (
	ID NUMERIC (7) PRIMARY KEY,
	NOME VARCHAR(30)
);

SAVEPOINT A;
INSERT INTO EXEMPLO VALUES (1,'LINHA1');

SAVEPOINT B;
INSERT INTO EXEMPLO VALUES (2,'LINHA2');

SAVEPOINT C;
INSERT INTO EXEMPLO VALUES (3,'LINHA3');

SELECT * FROM EXEMPLO;

DROP TABLE EXEMPLO;

ROLLBACK
ROLLBACK TO C;
ROLLBACK TO B;
ROLLBACK TO A;
COMMIT;