--Retorna todas as colunas da tabela;
SELECT * 
FROM EMPREGADO;
--Selecionando apenas linhas expecificas;
SELECT PRIM_NOME,ULT_NOME,SALARIO 
FROM EMPREGADO;
--Selecionando apenas linhas expecificas + salario multiplicado por 12;
SELECT PRIM_NOME,ULT_NOME,SALARIO*12 
FROM EMPREGADO;
--Concatenando;
SELECT PRIM_NOME || ' ' || ULT_NOME AS Nome,SALARIO,SALARIO*12 "Salario Anual"
FROM EMPREGADO;

SELECT 'ALO', 5 + 9, NOW(), PRIM_NOME || ' ' || SALARIO
FROM EMPREGADO;

--CREADO TABELA A PARTIR DE UM SELECT;
SELECT * INTO COPIAREGIAO
FROM REGIAO;
--CRIANDO UMA VIEW A PARTIR DE UM SELECT;
CREATE VIEW VREGIAO AS SELECT * FROM COPIAREGIAO;

SELECT * FROM COPIAREGIAO;

--MANIPULAÇÃO DE DADOS PELA VISÃO;
INSERT INTO VREGIAO VALUES(3,'REGIAO VIEW');