-- BEGIN implícito
INSERT INTO CURSO (CODIGOCURSO,NOME,DATACRIACAO) VALUES (5,'Engenharia de Computação',NULL);
-- COMMIT implícito
SELECT * FROM CURSO; --Dados atuais;
BEGIN;
INSERT INTO CURSO (CODIGOCURSO,NOME,DATACRIACAO) VALUES(6,'PSICOLOGIA', NULL);
SELECT * FROM CURSO; --Dados após a inserção;
ROLLBACK;
END;
SELECT * FROM CURSO;--Dados apos desfazer a transação;

SELECT * FROM DISCIPLINA;
BEGIN;
UPDATE DISCIPLINA SET CARGAHORARIA = CARGAHORARIA*1.2 WHERE CARGAHORARIA = 60;
UPDATE DISCIPLINA SET CARGAHORARIA = CARGAHORARIA*1.1 WHERE CARGAHORARIA = 40;
SELECT*FROM DISCIPLINA;
COMMIT;

BEGIN;
UPDATE DISCIPLINA SET CARGAHORARIA = CARGAHORARIA*1.2 WHERE CARGAHORARIA = 60;
SAVEPOINT CARGA60;
UPDATE DISCIPLINA SET CARGAHORARIA = CARGAHORARIA*1.1 WHERE CARGAHORARIA = 40;
ROLLBACK TO CARGA60;
SELECT*FROM DISCIPLINA;

--Comando para determinar o tipo de transação(Read only ou read write);
BEGIN;
SET TRANSACTION READ ONLY;
UPDATE DISCIPLINA SET CARGAHORARIA = 60;
ROLLBACK;
COMMIT;