CREATE TABLE ALUNO (
	CODIGOALUNO int NOT NULL,
	NOME varchar(90) NOT NULL,
	SEXO char(1) NOT NULL,
	DTNASCIMENTO date NOT NULL,
	EMAIL varchar(30) NULL,
	CONSTRAINT ALUNO_pk PRIMARY KEY (CODIGOALUNO)
);

INSERT INTO ALUNO (CODIGOALUNO,NOME,SEXO,DTNASCIMENTO,EMAIL) VALUES (1,'JOSÉ FRANCISCO TERRA','M','28/10/1989','JFT@GMAIL.COM');
INSERT INTO ALUNO (CODIGOALUNO,NOME,SEXO,DTNASCIMENTO,EMAIL) VALUES (2,'ANDREY COSTA FILHO','M','20/10/1999','ANDREYCF@HOTMAIL.COM');
INSERT INTO ALUNO (CODIGOALUNO,NOME,SEXO,DTNASCIMENTO,EMAIL) VALUES (3,'PATRÍCIA TORRES LOUREIRO','F','20/10/1980','PTORRES@GMAIL.COM');
INSERT INTO ALUNO (CODIGOALUNO,NOME,SEXO,DTNASCIMENTO,EMAIL) VALUES (4,'CARLA MARIA MACIEL','F','20/11/1996',NULL);
INSERT INTO ALUNO (CODIGOALUNO,NOME,SEXO,DTNASCIMENTO,EMAIL) VALUES (5,'LEILA SANTANA COSTA','F','20/11/2001',NULL);

--Selecionar tudo da tabela;
SELECT * FROM ALUNO;
--Selecionar o código, o nome e a data de nascimento de todos os alunos;
SELECT CODIGOALUNO, NOME, DTNASCIMENTO
FROM ALUNO;
SELECT CODIGOALUNO AS "Matrícula",
NOME AS "Nome do discente",
DTNASCIMENTO AS "Data de nascimento"
FROM ALUNO;

--Funções de data e hora;
SELECT CURRENT_DATE AS "DATA ATUAL",
	   CURRENT_TIME AS "HORA ATUAL",
	   CURRENT_TIMESTAMP "DATA E HORA ATUAIS",
	   EXTRACT( DOY FROM CURRENT_DATE) AS "DIA DO ANO",
 	   --DIAS DA SEMANA--
	   EXTRACT(DOW FROM CURRENT_DATE) AS "DIAS DA SEMANA",
	   EXTRACT(DAY FROM CURRENT_DATE) AS "DIA ATUAL",	   
	   EXTRACT(MONTH FROM CURRENT_DATE) AS "MÊS ATUAL",	   
	   EXTRACT(YEAR FROM CURRENT_DATE) AS "ANO ATUAL",	   
	   EXTRACT(CENTURY FROM CURRENT_DATE) AS "SÉCULO ATUAL";  
	   
--Exibindo o nome do dia da semana;
SELECT CASE WHEN EXTRACT(DOW FROM CURRENT_DATE) = 0 THEN 'DOMINGO'
			WHEN EXTRACT(DOW FROM CURRENT_DATE) = 1 THEN 'SEGUNDA'
			WHEN EXTRACT(DOW FROM CURRENT_DATE) = 2 THEN 'TERÇA' 			
			WHEN EXTRACT(DOW FROM CURRENT_DATE) = 3 THEN 'QUARTA'			
			WHEN EXTRACT(DOW FROM CURRENT_DATE) = 4 THEN 'QUINTA' 			
			WHEN EXTRACT(DOW FROM CURRENT_DATE) = 5 THEN 'SEXTA'			
			WHEN EXTRACT(DOW FROM CURRENT_DATE) = 6 THEN 'SÁBADO'
		END AS "NOME DO DIA DA SEMANA";
--Calculando a idade dos alunos;
SELECT NOME,
	   DTNASCIMENTO,
	   AGE(DTNASCIMENTO) AS "IDADE [ANO/MÊS/DIA]",
	   EXTRACT(YEAR FROM AGE(DTNASCIMENTO)) AS "IDADE DO ALUNO"
FROM ALUNO;
--Exibindo o nome, a idade e a faixa etaria dos alunos;
SELECT  NOME,
		EXTRACT(YEAR FROM AGE(DTNASCIMENTO)) AS "IDADE DO ALUNO",
		CASE WHEN EXTRACT(YEAR FROM AGE(DTNASCIMENTO)) <=20 THEN '1.ATÉ OS 20 ANOS'
			 WHEN EXTRACT(YEAR FROM AGE(DTNASCIMENTO)) BETWEEN 21 AND 30 THEN '2. 21 ATÉ OS 30 ANOS'
			 WHEN EXTRACT(YEAR FROM AGE(DTNASCIMENTO)) BETWEEN 31 AND 40 THEN '3. 31 ATÉ OS 40 ANOS'
			 WHEN EXTRACT(YEAR FROM AGE(DTNASCIMENTO)) BETWEEN 41 AND 50 THEN '4. 41 ATÉ OS 50 ANOS'
			 WHEN EXTRACT(YEAR FROM AGE(DTNASCIMENTO)) BETWEEN 51 AND 60 THEN '5. 51 ATÉ OS 60 ANOS'
		END AS "FAIXA ETÁRIA"
FROM ALUNO;
--Funcões de resumo;
SELECT
	COUNT(*) AS "NÚMERO DE ALUNOS",
	MIN(EXTRACT(YEAR FROM AGE(DTNASCIMENTO))) AS "MENOR DE IDADE",
	AVG(EXTRACT(YEAR FROM AGE(DTNASCIMENTO))) AS "IDADE MÉDIA",
	MAX(EXTRACT(YEAR FROM AGE(DTNASCIMENTO))) AS "MAIOR DE IDADE",
	SUM(EXTRACT(YEAR FROM AGE(DTNASCIMENTO)))/COUNT(*) AS "IDADE MEDIA"
FROM ALUNO;

--listando resumo em uma linha;
SELECT COUNT(*) NCURSOS FROM CURSO;
SELECT COUNT(*) NDISCIPINAS FROM DISCIPLINA;
SELECT COUNT(*) NALUNOS FROM ALUNO;

--Listando os 3 em apenas 1 linha;
SELECT
(SELECT COUNT(*) NCURSOS FROM CURSO),
(SELECT COUNT(*) NDISCIPINAS FROM DISCIPLINA),
(SELECT COUNT(*) NALUNOS FROM ALUNO);
--criando tabela  apartir de consulta;
CREATE TABLE TESTE AS
SELECT NOME,
	   EXTRACT(YEAR FROM AGE(DTNASCIMENTO)) AS "IDADE ALUNO",
	   CASE WHEN EXTRACT(YEAR FROM AGE(DTNASCIMENTO)) <= 20 THEN '1. ATÉ 20 ANOS'
	   		WHEN EXTRACT(YEAR FROM AGE(DTNASCIMENTO)) BETWEEN 21 AND 30 THEN '2. 21 A 30 ANOS'
			WHEN EXTRACT(YEAR FROM AGE(DTNASCIMENTO)) BETWEEN 31 AND 40 THEN '3. 31 A 40 ANOS'
			WHEN EXTRACT(YEAR FROM AGE(DTNASCIMENTO)) BETWEEN 41 AND 50 THEN '4. 41 A 50 ANOS'
			WHEN EXTRACT(YEAR FROM AGE(DTNASCIMENTO)) BETWEEN 51 AND 60 THEN '5. 51 A 60 ANOS'
			WHEN EXTRACT(YEAR FROM AGE(DTNASCIMENTO)) > 60 THEN '6. MAIS DE 60 ANOS'
		END AS "FAIXA ETÁRIA"
FROM ALUNO;
SELECT * FROM TESTE;
--Creando view;
CREATE VIEW VTESTE AS
SELECT NOME,
	   EXTRACT(YEAR FROM AGE(DTNASCIMENTO)) AS "IDADE ALUNO",
	   CASE WHEN EXTRACT(YEAR FROM AGE(DTNASCIMENTO)) <= 20 THEN '1. ATÉ 20 ANOS'
	   		WHEN EXTRACT(YEAR FROM AGE(DTNASCIMENTO)) BETWEEN 21 AND 30 THEN '2. 21 A 30 ANOS'
			WHEN EXTRACT(YEAR FROM AGE(DTNASCIMENTO)) BETWEEN 31 AND 40 THEN '3. 31 A 40 ANOS'
			WHEN EXTRACT(YEAR FROM AGE(DTNASCIMENTO)) BETWEEN 41 AND 50 THEN '4. 41 A 50 ANOS'
			WHEN EXTRACT(YEAR FROM AGE(DTNASCIMENTO)) BETWEEN 51 AND 60 THEN '5. 51 A 60 ANOS'
			WHEN EXTRACT(YEAR FROM AGE(DTNASCIMENTO)) > 60 THEN '6. MAIS DE 60 ANOS'
		END AS "FAIXA ETÁRIA"
FROM ALUNO;
SELECT * FROM TESTE;