CREATE TABLE DEPARTAMENTO (
 	CODIGODEPARTAMENTO int NOT NULL,
 	NOME varchar(90) NOT NULL,
 	CONSTRAINT DEPARTAMENTO_pk PRIMARY KEY (CODIGODEPARTAMENTO)
);
 
CREATE TABLE FUNCIONARIO (
 	CODIGOFUNCIONARIO int NOT NULL,
 	NOME varchar(90) NOT NULL,
 	CPF char(15) NULL,
 	SEXO char(1) NOT NULL,
 	DTNASCIMENTO date NOT NULL,
 	SALARIO real NULL,
 	CODIGODEPARTAMENTO int NULL,
	CONSTRAINT FUNCIONARIO_pk PRIMARY KEY (CODIGOFUNCIONARIO)
);

ALTER TABLE FUNCIONARIO ADD CONSTRAINT FUNCIONARIO_DEPARTAMENTO
 FOREIGN KEY (CODIGODEPARTAMENTO)
 REFERENCES DEPARTAMENTO (CODIGODEPARTAMENTO) ;
 
INSERT INTO DEPARTAMENTO(CODIGODEPARTAMENTO,NOME) VALUES(1,'Tecnologia da Informação');
INSERT INTO DEPARTAMENTO(CODIGODEPARTAMENTO,NOME) VALUES(2,'Contabilidade');
INSERT INTO DEPARTAMENTO(CODIGODEPARTAMENTO,NOME) VALUES(3,'Marketing');
INSERT INTO FUNCIONARIO (CODIGOFUNCIONARIO, NOME, CPF, SEXO,DTNASCIMENTO, SALARIO,CODIGODEPARTAMENTO) VALUES (1,'ROBERTA SILVA BRASIL',NULL,'F','20/02/1980',7000,1);
INSERT INTO FUNCIONARIO (CODIGOFUNCIONARIO, NOME, CPF, SEXO,DTNASCIMENTO, SALARIO,CODIGODEPARTAMENTO) VALUES (2,'MARIA SILVA BRASIL',NULL,'F','20/09/1988',9500,2);
INSERT INTO FUNCIONARIO (CODIGOFUNCIONARIO, NOME, CPF, SEXO,DTNASCIMENTO, SALARIO,CODIGODEPARTAMENTO) VALUES (3,'GABRIELLA PEREIRA LIMA',NULL,'F','20/02/1990',6000,1);
INSERT INTO FUNCIONARIO (CODIGOFUNCIONARIO, NOME, CPF, SEXO,DTNASCIMENTO, SALARIO,CODIGODEPARTAMENTO) VALUES (4,'MARCOS PEREIRA BRASIL',NULL,'M','20/02/1999',6000,2);
INSERT INTO FUNCIONARIO (CODIGOFUNCIONARIO, NOME, CPF, SEXO,DTNASCIMENTO, SALARIO,CODIGODEPARTAMENTO) VALUES (5,'HEMERSON SILVA BRASIL',NULL,'M','20/12/1992',4000,NULL);

SELECT * FROM DEPARTAMENTO;
SELECT * FROM FUNCIONARIO;
TABLE FUNCIONARIO; 

SELECT CODIGOFUNCIONARIO,NOME,SALARIO
FROM FUNCIONARIO
WHERE SALARIO= (
	SELECT MAX(SALARIO)
	FROM FUNCIONARIO);

SELECT CODIGOFUNCIONARIO,NOME,SALARIO
FROM FUNCIONARIO
WHERE SALARIO>(
	SELECT AVG(SALARIO)
	FROM FUNCIONARIO
);

SELECT CODIGOFUNCIONARIO, NOME, SALARIO
FROM FUNCIONARIO
WHERE SALARIO < (
	
	SELECT AVG(SALARIO)
	FROM FUNCIONARIO
	WHERE CODIGODEPARTAMENTO IN (
		
		SELECT CODIGODEPARTAMENTO
		FROM DEPARTAMENTO
		WHERE NOME='Tecnologia da Informação'
));

SELECT CODIGOFUNCIONARIO, NOME, SALARIO
FROM FUNCIONARIO
WHERE SALARIO < (
	
	SELECT AVG(SALARIO)
	FROM FUNCIONARIO F JOIN DEPARTAMENTO D ON 
	(F.CODIGODEPARTAMENTO=D.CODIGODEPARTAMENTO)
	WHERE D.NOME = 'Tecnologia da Informação');
	
SELECT COUNT(*) AS QUANTIDADE
FROM FUNCIONARIO
WHERE SALARIO < (
	SELECT AVG(SALARIO)
	FROM FUNCIONARIO
	WHERE SEXO='F');
);

SELECT CODIGOFUNCIONARIO,NOME,SALARIO
FROM FUNCIONARIO F
WHERE SALARIO>(
	SELECT AVG(SALARIO)
	FROM FUNCIONARIO
	WHERE CODIGODEPARTAMENTO=F.CODIGODEPARTAMENTO
);
 
SELECT CODIGOFUNCIONARIO,NOME,SALARIO
FROM FUNCIONARIO F
 	 JOIN (
		 SELECT CODIGODEPARTAMENTO,AVG(SALARIO) AS MEDIA
		 FROM FUNCIONARIO
		 GROUP BY CODIGODEPARTAMENTO) TESTE
	ON F.CODIGODEPARTAMENTO=TESTE.CODIGODEPARTAMENTO
WHERE SALARIO>MEDIA;

UPDATE FUNCIONARIO F
SET SALARIO = (
	SELECT MAX(SALARIO)
	FROM FUNCIONARIO
	WHERE CODIGODEPARTAMENTO=F.CODIGODEPARTAMENTO
)
WHERE F.CODIGODEPARTAMENTO IS NOT NULL;

SELECT D.CODIGODEPARTAMENTO, D.NOME
FROM DEPARTAMENTO D
WHERE NOT EXISTS (
	SELECT F.CODIGODEPARTAMENTO
	FROM FUNCIONARIO F
	WHERE D.CODIGODEPARTAMENTO=F.CODIGODEPARTAMENTO
);