CREATE TABLE FUNCIONARIO (
	CODIGOFUNCIONARIO int NOT NULL,
	NOME varchar(90) NOT NULL,
	CPF CHAR(15) NULL,
	SEXO CHAR(1) NOT NULL,
	DTNASCIMENTO date NOT NULL,
	SALARIO real NULL,
	CONSTRAINT FUNCIONARIO_PK PRIMARY KEY (CODIGOFUNCIONARIO)
);

INSERT INTO FUNCIONARIO (CODIGOFUNCIONARIO, NOME, CPF, SEXO, DTNASCIMENTO, SALARIO) VALUES (1,'ROBERTA SILVA BRASIL',NULL,'F','20/02/1980',7000);
INSERT INTO FUNCIONARIO (CODIGOFUNCIONARIO, NOME, CPF, SEXO, DTNASCIMENTO, SALARIO) VALUES (2,'MARIA SILVA BRASIL',NULL,'F','20/09/1988',9500);
INSERT INTO FUNCIONARIO (CODIGOFUNCIONARIO, NOME, CPF, SEXO, DTNASCIMENTO, SALARIO) VALUES (3,'GABRIELLA PEREIRA LIMA',NULL,'F','20/02/1990',6000);
INSERT INTO FUNCIONARIO (CODIGOFUNCIONARIO, NOME, CPF, SEXO, DTNASCIMENTO, SALARIO) VALUES (4,'MARCOS PEREIRA BRASIL',NULL,'M','20/02/1999',6000);
INSERT INTO FUNCIONARIO (CODIGOFUNCIONARIO, NOME, CPF, SEXO, DTNASCIMENTO, SALARIO) VALUES (5,'HEMERSON SILVA BRASIL',NULL,'M','20/12/1992',4000);

SELECT * FROM FUNCIONARIO;

SELECT DISTINCT SEXO
FROM FUNCIONARIO;

SELECT SEXO 
FROM FUNCIONARIO
ORDER BY SEXO;

SELECT SEXO, COUNT(*) AS QUANTIDADE
FROM FUNCIONARIO
GROUP BY SEXO;

SELECT SEXO, 
	   AVG(SALARIO) AS MEDIASALARIAL
FROM FUNCIONARIO
GROUP BY SEXO;

SELECT EXTRACT(MONTH FROM DTNASCIMENTO) AS MES,
	   COUNT(*) AS QUANTIDADE,
	   MIN(SALARIO) AS MENORSALARIO,
	   ROUND(AVG(SALARIO)::NUMERIC,0) AS MEDIASALARIAL,
	   MAX(SALARIO) AS MAIORSALARIO
FROM FUNCIONARIO
GROUP BY EXTRACT(MONTH FROM DTNASCIMENTO)
ORDER BY EXTRACT(MONTH FROM DTNASCIMENTO);

SELECT EXTRACT(MONTH FROM DTNASCIMENTO) AS MES,
	   SEXO,
	   COUNT(*) AS QUANTIDADE
FROM FUNCIONARIO
GROUP BY EXTRACT(MONTH FROM DTNASCIMENTO),SEXO
ORDER BY EXTRACT(MONTH FROM DTNASCIMENTO);

SELECT EXTRACT(MONTH FROM DTNASCIMENTO) AS MES,
	   COUNT(*) AS QUANTIDADE,
	   SUM(SALARIO*0.5) AS TOTALBONUS
FROM FUNCIONARIO
GROUP BY EXTRACT(MONTH FROM DTNASCIMENTO)
HAVING COUNT(*) > 1
ORDER BY EXTRACT (MONTH FROM DTNASCIMENTO);
	   