CREATE TABLE FUNCIONARIO (
	CODIGOFUNCIONARIO int NOT NULL,
	NOME varchar(90) NOT NULL,
	CPF char(15) NULL,
	SEXO char(1) NOT NULL,
	DTNASCIMENTO date NOT NULL,
	SALARIO real NULL,
	CONSTRAINT FUNCIONARIO_pk PRIMARY KEY (CODIGOFUNCIONARIO)
);

CREATE TABLE ALUNO(
	CODIGOALUNO int NOT NULL,
	NOME varchar(90) NOT NULL,
	CPF char(15) NOT NULL,
	SEXO char(1) NOT NULL,
	DTNASCIMENTO date NOT NULL,
CONSTRAINT ALUNO_pk PRIMARY KEY (CODIGOALUNO)
);

CREATE TABLE CLIENTE(
	CODIGOCLIENTE int NOT NULL,
	NOME varchar(90) NOT NULL,
	CPF char(15) NOT NULL,
	SEXO char(1) NOT NULL,
CONSTRAINT CLIENTE_pk PRIMARY KEY (CODIGOCLIENTE)
);

INSERT INTO FUNCIONARIO (CODIGOFUNCIONARIO, NOME, CPF, SEXO, DTNASCIMENTO, SALARIO) VALUES (1,'ROBERTA SILVA BRASIL','82998','F','20/02/1980',7000);
INSERT INTO FUNCIONARIO (CODIGOFUNCIONARIO, NOME, CPF, SEXO, DTNASCIMENTO, SALARIO) VALUES (2,'MARIA SILVA BRASIL','9876','F','20/09/1988',9500);
INSERT INTO FUNCIONARIO (CODIGOFUNCIONARIO, NOME, CPF, SEXO, DTNASCIMENTO, SALARIO) VALUES (3,'GABRIELLA PEREIRA LIMA','32998','F','20/02/1990',6000);
INSERT INTO FUNCIONARIO (CODIGOFUNCIONARIO, NOME, CPF, SEXO, DTNASCIMENTO, SALARIO) VALUES (4,'MARCOS PEREIRA BRASIL','9999','M','20/02/1999',6000);
INSERT INTO FUNCIONARIO (CODIGOFUNCIONARIO, NOME, CPF, SEXO, DTNASCIMENTO, SALARIO) VALUES (5,'HEMERSON SILVA BRASIL','9111','M','20/12/1992',4000);

INSERT INTO ALUNO (CODIGOALUNO, NOME, CPF, SEXO, DTNASCIMENTO) VALUES (1,'JOSÉ FRANCISCO TERRA','82988','M','28/10/1989');
INSERT INTO ALUNO (CODIGOALUNO, NOME, CPF, SEXO, DTNASCIMENTO) VALUES (2,'ANDREY COSTA FILHO','0024','M','20/10/1999');
INSERT INTO ALUNO (CODIGOALUNO, NOME, CPF, SEXO, DTNASCIMENTO) VALUES (3,'ROBERTA SILVA BRASIL','82998','F','20/02/1980');
INSERT INTO ALUNO (CODIGOALUNO, NOME, CPF, SEXO, DTNASCIMENTO) VALUES (4,'CARLA MARIA MACIEL','0044','F','20/11/1996');
INSERT INTO ALUNO (CODIGOALUNO, NOME, CPF, SEXO, DTNASCIMENTO) VALUES (5,'MARCOS PEREIRA BRASIL','9999','M','20/02/1999');

INSERT INTO CLIENTE (CODIGOCLIENTE, NOME, CPF, SEXO) VALUES (1,'ROBERTA SILVA BRASIL','82998','F');
INSERT INTO CLIENTE (CODIGOCLIENTE, NOME, CPF, SEXO) VALUES (2,'MARCOS PEREIRA BRASIL','9999','M');
INSERT INTO CLIENTE (CODIGOCLIENTE, NOME, CPF, SEXO) VALUES (3,'HEMERSON SILVA BRASIL','9111','M'); 

--Uso do comando UNION;
SELECT NOME, CPF
FROM FUNCIONARIO
UNION
SELECT NOME, CPF
FROM CLIENTE;

--Uso do comando UNION ALL;
SELECT NOME, CPF
FROM FUNCIONARIO
UNION ALL
SELECT NOME, CPF
FROM CLIENTE;

--Uso do comando UNION ALL EXPECIFICANDO A ORIGEM;
SELECT NOME, CPF, 'Dados da tabela funcinario' AS ORIGEM
FROM FUNCIONARIO
UNION ALL 
SELECT NOME, CPF, 'Dados da tabela cliente' AS ORIGEM
FROM CLIENTE;

--USO DO INTERSECT;
SELECT NOME, CPF
FROM FUNCIONARIO
INTERSECT
SELECT NOME, CPF
FROM CLIENTE;

SELECT NOME, CPF
FROM FUNCIONARIO
INTERSECT
SELECT NOME, CPF
FROM CLIENTE
INTERSECT
SELECT NOME, CPF
FROM ALUNO;

SELECT NOME, CPF
FROM FUNCIONARIO
UNION
SELECT NOME, CPF
FROM CLIENTE
INTERSECT
SELECT NOME, CPF
FROM ALUNO;

--USO DO EXCEPT
SELECT NOME, CPF
FROM FUNCIONARIO
EXCEPT
SELECT NOME, CPF
FROM CLIENTE;


SELECT NOME, CPF
FROM CLIENTE
EXCEPT
SELECT NOME, CPF
FROM FUNCIONARIO;

SELECT NOME, CPF
FROM FUNCIONARIO
EXCEPT
SELECT NOME, CPF
FROM CLIENTE
EXCEPT
SELECT NOME, CPF
FROM ALUNO;