CREATE TABLE ALUNO (
	CODIGOALUNO int NOT NULL,
	NOME varchar(90) NOT NULL,
	SEXO char(1) NOT NULL,
	DTNASCIMENTO date NOT NULL,
	EMAIL varchar(30) NULL,
	CONSTRAINT ALUNO_pk PRIMARY KEY (CODIGOALUNO)
);

INSERT INTO ALUNO (CODIGOALUNO,NOME,SEXO,DTNASCIMENTO,EMAIL) VALUES (1,'JOSÉ FRANCISCO TERRA','M','28/10/1989','JFT@GMAIL.COM');
INSERT INTO ALUNO (CODIGOALUNO,NOME,SEXO,DTNASCIMENTO,EMAIL) VALUES (2,'ANDREY COSTA FILHO','M','20/10/1999','ANDREYCF@HOTMAIL.COM');
INSERT INTO ALUNO (CODIGOALUNO,NOME,SEXO,DTNASCIMENTO,EMAIL) VALUES (3,'PATRÍCIA TORRES LOUREIRO','F','20/10/1980','PTORRES@GMAIL.COM');
INSERT INTO ALUNO (CODIGOALUNO,NOME,SEXO,DTNASCIMENTO,EMAIL) VALUES (4,'CARLA MARIA MACIEL','F','20/11/1996',NULL);
INSERT INTO ALUNO (CODIGOALUNO,NOME,SEXO,DTNASCIMENTO,EMAIL) VALUES (5,'LEILA SANTANA COSTA','F','20/11/2001',NULL);

SELECT NOME, DTNASCIMENTO
FROM ALUNO
WHERE SEXO='F';

SELECT NOME, DTNASCIMENTO
FROM ALUNO
WHERE SEXO='F' AND EXTRACT (MONTH FROM DTNASCIMENTO)=11;

SELECT NOME, DTNASCIMENTO
FROM ALUNO
WHERE EXTRACT (MONTH FROM DTNASCIMENTO) IN (7,8,9,10,11,12);

SELECT NOME
FROM ALUNO
WHERE EXTRACT (YEAR FROM DTNASCIMENTO) BETWEEN 1985 AND 2005;

SELECT NOME
FROM ALUNO
WHERE EXTRACT (YEAR FROM DTNASCIMENTO) >= 1985 AND EXTRACT (YEAR FROM DTNASCIMENTO)<= 2005;

SELECT NOME
FROM ALUNO 
WHERE NOME LIKE '%COSTA%';

SELECT NOME
FROM ALUNO
WHERE NOME LIKE '_A%';

SELECT NOME
FROM ALUNO
WHERE NOME NOT LIKE '%MARIA%';

SELECT COUNT(*) AS "QUANTIDADE"
FROM ALUNO
WHERE EMAIL LIKE '%@GMAIL.%';

SELECT NOME, DTNASCIMENTO, EMAIL
FROM ALUNO
WHERE EMAIL IS NOT NULL;

SELECT NOME, DTNASCIMENTO
FROM ALUNO
ORDER BY NOME;

SELECT NOME, DTNASCIMENTO
FROM ALUNO
ORDER BY EXTRACT (MONTH FROM DTNASCIMENTO), NOME;